name: Release Workflow
on:
  release:
    types: [published]
permissions: read-all
jobs:
  run-python-test:
    name: Unit tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.14]
    
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: run tests
        run: python -m pytest tests/
  
  deploy-to-pypi:
    name: Deploy to GitHub and PyPI
    runs-on: ubuntu-latest
    needs: run-python-test

    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.14

      - name: install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: install project dependencies
        run: |
          pip install .

      - name: build package
        run: python -m build