name: CI

on:
  release:
    types: [published]
  
permissions: write-all

jobs:

  test:
    name: Unit tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.14]
    
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: run tests
        run: python -m pytest tests/
  
  deploy:
    name: Deploy to GitHub and PyPI
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14

      - name: install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: install project dependencies
        run: |
          pip install .

      - name: build package
        run: python -m build

      - name: publish to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}