name: CI

on:
  release:
    types: [published, released]
  
  workflow_dispatch:

permissions: write-all

jobs:

  test:
    name: Unit tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.14]
    
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: run tests
        run: python -m pytest tests/
