name: TEST

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-python-test:
    name: run unit tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.14]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
              ${{ runner.os }}-pip-

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: run tests
        run: python -m pytest tests/
  